name: Test BasedGram

on: [push]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: lab_04_env
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet restore

      - name: 'Create env file'
        shell: bash
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          VERIFICATION_CODE: ${{ secrets.VERIFICATION_CODE }}
        run: |
          echo "SMTP_HOST=${SMTP_HOST}" >> .env
          echo "USER_EMAIL=${USER_EMAIL}" >> .env
          echo "SENDER_EMAIL=${SENDER_EMAIL}" >> .env
          echo "EMAIL_PASSWORD=${EMAIL_PASSWORD}" >> .env
          echo "VERIFICATION_CODE=${VERIFICATION_CODE}" >> .env

      - name: Run static analysis
        run: make static-analysis

      - name: Run unit tests
        run: make unit-tests

      - name: Run integration tests
        if: '!failure()'
        run: make integration-tests

      - name: Run e2e tests
        if: '!failure()'
        run: make e2e-tests
  
      - name: Processing report data
        run: make concat-reports -i
        if: always()
        continue-on-error: true

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history